export const VALID_ROLES = [
  'USER',
  'MODERATOR',
  'CREATOR',
  'SUPPORT',
  'ADMIN',
  'SUPERADMIN',
];

export const ADMIN_ROLES = ['ADMIN', 'SUPERADMIN'];
export const MODERATOR_ROLES = ['MODERATOR', 'ADMIN', 'SUPERADMIN'];
export const SUPPORT_ROLES = ['SUPPORT', 'ADMIN', 'SUPERADMIN'];
export const CREATOR_ROLES = ['CREATOR', 'ADMIN', 'SUPERADMIN'];
